### ISSUE TITLE
Digest of wiz-broker images not publicly available

### ISSUE THREAD

**Issue by Flektoma** [wiz-sec/charts#104]
Hi,

as part of deployment to company internal infrastructure, I will need to mirror wiz-broker docker image into private company docker registry. To do it safely, I would like to verify that image that is being mirrored has correct digest as the one officially released by Wiz.io.

Is there a place where I can verify which versions of Wiz docker images are available (with change log ideally) and what is `digest` for each of them so I can verify?

Sadly, I have not found an answer in Wiz documentation so I am trying my luck here.

Thank you!

**Comment by lir-wiz** [comment]
Hi @Flektoma, our container images are signed using Cosign. You can verify the container image signature to make sure it is valid and reliable.
https://docs.wiz.io/wiz-docs/docs/artifact-validation
