### ISSUE TITLE
Feature Request: wiz-sensor - Provide easier correlation of event to cluster

### ISSUE THREAD

**Issue by agrewel** [wiz-sec/charts#125]
With the Wiz cluster connector we were able to set the connector name in the Helm chart. This allowed us to use cluster name as connector name and made identifying the cluster related to a finding easier. Please provide something similar for the sensor chart. Right now the helm connectors appear to be randomly named, so if we could name them after the cluster as we do for the cluster connector our lives would be easier.

**Comment by ariknem** [comment]
If your cluster is connected to Wiz agentless scanning we should automatically find the name after at most 24 hours. Is your cluster not connected in this way? This can sometimes happen in on-prem kubernetes solutions like openshift/rancher, etc.

**Comment by agrewel** [comment]
This is an on prem cluster running RKE. It uses wiz-sensor agent based scanning. The connector is named helm-XXXX where the XXXX appears to be a random string. It’s been up and running for several days so if it was going to detect the cluster name it would presumably already have done so.

From: Arik Nemtsov ***@***.***>
Date: Sunday, June 18, 2023 at 3:41 AM
To: wiz-sec/charts ***@***.***>
Cc: Aaron Grewell ***@***.***>, Author ***@***.***>
Subject: Re: [wiz-sec/charts] Feature Request: wiz-sensor - Provide easier correlation of event to cluster (Issue #125)
If your cluster is connected to Wiz agentless scanning we should automatically find the name after at most 24 hours. Is your cluster not connected in this way? This can sometimes happen in on-prem kubernetes solutions like openshift/rancher,
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

If your cluster is connected to Wiz agentless scanning we should automatically find the name after at most 24 hours. Is your cluster not connected in this way? This can sometimes happen in on-prem kubernetes solutions like openshift/rancher, etc.

**Comment by ariknem** [comment]
Thanks.

We will add this option, but it will take us a few weeks.

**Comment by ariknem** [comment]
This is released in chart version 1.0.2280 of the sensor
