### ISSUE TITLE
ArgoCD keeps creating new connectors with `autoCreateConnector.enabled = true`

### ISSUE THREAD

**Issue by NitriKx** [wiz-sec/charts#137]
As ArgoCD considers the `pre-install` and `pre-upgrade` Helm lifecycle hooks as a `PreSync` operations, the connector creation job is run on EVERY ArgoCD sync. 

Any ideas on how to fix that? 
One nice solution would be to make the `wiz-broker` tool to only generates new credentials/update the K8S secrets if: 
- the chart version has changed (could be stored in the secret) 
- we pass a `--force-recreation` flag to the `wiz-broker` CLI 

If the `wiz-broker` is opensource, I can propose a PR on it with this change.

**Comment by lir-wiz** [comment]
Hi @NitriKx, we have made some changes to the chart, making sure Argo does not mark the application as out of sync of every check. We have also fixed a bug that was causing connectors to be re-generated on every sync.
Please let us know if you are still having issues with our charts and Argo CD.
