### ISSUE TITLE
Bug with apiTokenSecretName for wiz-kubernetes-connector chart

### ISSUE THREAD

**Issue by JoseAlvarezSonos** [wiz-sec/charts#147]
After updating our `wiz-kubernetes-connector` to version `2.2.8` I realized that the apiTokenSecret name was not getting properly generated. It seems that there is a new `global` key, which is fine, but in the [helper function](https://github.com/wiz-sec/charts/blob/a33c8840f379ee6f91fcffef5deb7e89403b1a40/wiz-kubernetes-connector/templates/_helpers.tpl#L64) to generate the name for the apiTokenSecret there is a typo.

The key `.Values.global.wizApiToken.secret.name` is repeated, I think it should be:
```
{{- define "wiz-kubernetes-connector.apiTokenSecretName" -}}
{{- $nameOverride := coalesce .Values.global.wizApiToken.secret.name  .Values.wizApiToken.secret.name .Values.global.nameOverride .Values.nameOverride }}
{{- default .Chart.Name $nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}
```

Where the 2nd repeated `.Values.global.wizApiToken.secret.name` should be `.Values.wizApiToken.secret.name`.

**Comment by lir-wiz** [comment]
Thanks, @JoseAlvarezSonos !
