### ISSUE TITLE
"rollme" annotation of wiz-kubernetes-connector deployment prevents gitops use-cases

### ISSUE THREAD

**Issue by alfredkrohmer** [wiz-sec/charts#162]
This hard-coded annotation: https://github.com/wiz-sec/charts/blob/24c71158cf62abdf3c6879956bd4f4a0d59ab695/wiz-kubernetes-connector/templates/wiz-broker-deployment.yaml#L20
changes on every rendering of the Helm chart and therefor would trigger a redeployment / rollout on every reconciliation loop of gitops systems. This should be made optional.

**Comment by sstarcher** [comment]
This still seems to be an issue.  Is the intent for users to disable the rollme annotation?
https://github.com/wiz-sec/charts/blob/master/wiz-broker/templates/wiz-broker-deployment.yaml#L24
