### ISSUE TITLE
wiz-sensor should provide more context for the permissions and Linux capabilities defined in helm chart

### ISSUE THREAD

**Issue by adkafka** [wiz-sec/charts#254]
I see that we use `hostNetwork: true` here:
https://github.com/wiz-sec/charts/blob/7490fe38691691676806b76b5827054302000e86/wiz-sensor/templates/daemonset.yaml#L45

I experimented with setting this to `false`, and so far the daemonset seems healthy. Is this permission required? If it is required, can we document in detail why?

Additionally, the wiz-sensor helm chart currently defines the following capabilities:
https://github.com/wiz-sec/charts/blob/7490fe38691691676806b76b5827054302000e86/wiz-sensor/templates/daemonset.yaml#L70-L84

I appreciate that comments are added next to each capability, but many of them still leave me with questions. For example, why is `KILL` needed for forensics? Is `NET_ADMIN` required, or is there another capability that fits the needs of wiz-sensor without granting more access than required. I looked into `SYS_ADMIN` a bit and learned that it is required to call `setns` (https://man7.org/linux/man-pages/man2/setns.2.html). It would help to document the syscall(s) needed, and why wiz-sensor needs to make these calls.

Can we include more detail in these required capabilities?

**Comment by ariknem** [comment]
KILL is actually required for the upcoming blocking capabilities for the sensor. The reason we mention "forensics" is that we have an (unreleased) feature that signals processes for forensics purposes.

Similarly other caps we have are sometimes for future-proofing the deployment. Most customers install the helm chart once and then only update the image. Updating the helm chart is usually a manual operation (unless you have some gitops based updater).

If you're a Wiz customer feel free to reach out to support and we can engage with you for more details.
