### ISSUE TITLE
What is the public helm chart link?

### ISSUE THREAD

**Issue by danielkimuipath** [wiz-sec/charts#349]
How can I publicly pull the HELM charts?

For example, What is the URL for pulling the `wiz-kubernetes-integration` helm chart?

I would like to use curl to download helm chart, but I don't see information around it. Can someone clarify this for me? Thanks

**Comment by ariknem** [comment]
try this:
helm repo add wiz-sec https://charts.wiz.io/
you will have the wiz-kubernetes-integration chart there
